services:
  back:
    container_name: kor_back
    build: ./back
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_PASSWORD_FILE=/run/secrets/db-password
    env_file:
      - back/.env
      - db/.env
      - front/.env
    secrets:
      - db-password
    ports:
      - '3000:8080'
    volumes:
      - ./back/src:/src/go/github.com/SongCastle/KoR
    networks:
      - back_net
      - front_net
    depends_on:
      - db
    tty: true

  db:
    container_name: kor_db
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
    env_file:
      - db/.env
    secrets:
      - db-password
    networks:
      - back_net
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql

  front:
    container_name: kor_front
    build: ./front
    volumes:
      - ./front:/opt/front
      - no_modules:/opt/front/node_modules
    env_file:
      - back/.env
    networks:
      - front_net
    ports:
      - '8080:8080'
    depends_on:
      - back
    tty: true

volumes:
  no_modules:
secrets:
  db-password:
    file: db/password.txt
networks:
  back_net:
  front_net:
